/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Cassini_Assembly.glb -t -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'cassini_16Action' | 'cassini_10Action' | 'cassini_11Action' | 'cassini_13Action' | 'cassini_14Action' | 'cassini_15Action' | 'cassini_a1Action' | 'cassini_a2Action' | 'cassini_a4Action' | 'cassini_a5Action' | 'cassini_a6Action' | 'cassini_a7Action' | 'cassini_a8Action' | 'cassini_asAction'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    cassini_10_1: THREE.Mesh
    cassini_10_2: THREE.Mesh
    cassini_10_3: THREE.Mesh
    cassini_11_1: THREE.Mesh
    cassini_11_2: THREE.Mesh
    cassini_13_1: THREE.Mesh
    cassini_13_2: THREE.Mesh
    cassini_13_3: THREE.Mesh
    cassini_13_4: THREE.Mesh
    cassini_13_5: THREE.Mesh
    cassini_14: THREE.Mesh
    cassini_15_1: THREE.Mesh
    cassini_15_2: THREE.Mesh
    cassini_a1: THREE.Mesh
    cassini_a2_1: THREE.Mesh
    cassini_a2_2: THREE.Mesh
    cassini_a2_3: THREE.Mesh
    cassini_a4_1: THREE.Mesh
    cassini_a4_2: THREE.Mesh
    cassini_a4_3: THREE.Mesh
    cassini_a4_4: THREE.Mesh
    cassini_a5_1: THREE.Mesh
    cassini_a5_2: THREE.Mesh
    cassini_a5_3: THREE.Mesh
    cassini_a6: THREE.Mesh
    cassini_a7: THREE.Mesh
    cassini_a8_1: THREE.Mesh
    cassini_a8_2: THREE.Mesh
    cassini_a8_3: THREE.Mesh
    cassini_a8_4: THREE.Mesh
    cassini_as_1: THREE.Mesh
    cassini_as_2: THREE.Mesh
  }
  materials: {
    anod_aluminum: THREE.MeshStandardMaterial
    white: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    aluminum: THREE.MeshStandardMaterial
    gold: THREE.MeshStandardMaterial
    grey: THREE.MeshStandardMaterial
    silver: THREE.MeshStandardMaterial
    red_orange: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/../Cassini_Assembly.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="cassini_16">
          <group name="cassini_10">
            <mesh name="cassini_10_1" geometry={nodes.cassini_10_1.geometry} material={materials.anod_aluminum} />
            <mesh name="cassini_10_2" geometry={nodes.cassini_10_2.geometry} material={materials.white} />
            <mesh name="cassini_10_3" geometry={nodes.cassini_10_3.geometry} material={materials.black} />
          </group>
          <group name="cassini_11">
            <mesh name="cassini_11_1" geometry={nodes.cassini_11_1.geometry} material={materials.black} />
            <mesh name="cassini_11_2" geometry={nodes.cassini_11_2.geometry} material={materials.anod_aluminum} />
          </group>
          <group name="cassini_13">
            <mesh name="cassini_13_1" geometry={nodes.cassini_13_1.geometry} material={materials.aluminum} />
            <mesh name="cassini_13_2" geometry={nodes.cassini_13_2.geometry} material={materials.black} />
            <mesh name="cassini_13_3" geometry={nodes.cassini_13_3.geometry} material={materials.gold} />
            <mesh name="cassini_13_4" geometry={nodes.cassini_13_4.geometry} material={materials.grey} />
            <mesh name="cassini_13_5" geometry={nodes.cassini_13_5.geometry} material={materials.silver} />
          </group>
          <mesh name="cassini_14" geometry={nodes.cassini_14.geometry} material={materials.gold} />
          <group name="cassini_15">
            <mesh name="cassini_15_1" geometry={nodes.cassini_15_1.geometry} material={materials.silver} />
            <mesh name="cassini_15_2" geometry={nodes.cassini_15_2.geometry} material={materials.red_orange} />
          </group>
          <mesh name="cassini_a1" geometry={nodes.cassini_a1.geometry} material={materials.anod_aluminum} />
          <group name="cassini_a2">
            <mesh name="cassini_a2_1" geometry={nodes.cassini_a2_1.geometry} material={materials.white} />
            <mesh name="cassini_a2_2" geometry={nodes.cassini_a2_2.geometry} material={materials.silver} />
            <mesh name="cassini_a2_3" geometry={nodes.cassini_a2_3.geometry} material={materials.anod_aluminum} />
          </group>
          <group name="cassini_a4">
            <mesh name="cassini_a4_1" geometry={nodes.cassini_a4_1.geometry} material={materials.anod_aluminum} />
            <mesh name="cassini_a4_2" geometry={nodes.cassini_a4_2.geometry} material={materials.silver} />
            <mesh name="cassini_a4_3" geometry={nodes.cassini_a4_3.geometry} material={materials.black} />
            <mesh name="cassini_a4_4" geometry={nodes.cassini_a4_4.geometry} material={materials.grey} />
          </group>
          <group name="cassini_a5">
            <mesh name="cassini_a5_1" geometry={nodes.cassini_a5_1.geometry} material={materials.anod_aluminum} />
            <mesh name="cassini_a5_2" geometry={nodes.cassini_a5_2.geometry} material={materials.grey} />
            <mesh name="cassini_a5_3" geometry={nodes.cassini_a5_3.geometry} material={materials.silver} />
          </group>
          <mesh name="cassini_a6" geometry={nodes.cassini_a6.geometry} material={materials.anod_aluminum} />
          <mesh name="cassini_a7" geometry={nodes.cassini_a7.geometry} material={materials.silver} />
          <group name="cassini_a8">
            <mesh name="cassini_a8_1" geometry={nodes.cassini_a8_1.geometry} material={materials.silver} />
            <mesh name="cassini_a8_2" geometry={nodes.cassini_a8_2.geometry} material={materials.black} />
            <mesh name="cassini_a8_3" geometry={nodes.cassini_a8_3.geometry} material={materials.white} />
            <mesh name="cassini_a8_4" geometry={nodes.cassini_a8_4.geometry} material={materials.gold} />
          </group>
          <group name="cassini_as">
            <mesh name="cassini_as_1" geometry={nodes.cassini_as_1.geometry} material={materials.silver} />
            <mesh name="cassini_as_2" geometry={nodes.cassini_as_2.geometry} material={materials.gold} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/../Cassini_Assembly.glb')
