/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CassiniHuygensB.glb -t -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['0']: THREE.Mesh
    ['0-1']: THREE.Mesh
    ['10']: THREE.Mesh
    ['103']: THREE.Mesh
    ['104']: THREE.Mesh
    ['108']: THREE.Mesh
    ['11']: THREE.Mesh
    ['111']: THREE.Mesh
    ['112']: THREE.Mesh
    ['113']: THREE.Mesh
    ['116']: THREE.Mesh
    ['118']: THREE.Mesh
    ['119']: THREE.Mesh
    ['123']: THREE.Mesh
    ['13']: THREE.Mesh
    ['139']: THREE.Mesh
    ['14']: THREE.Mesh
    ['18']: THREE.Mesh
    ['19']: THREE.Mesh
    ['22']: THREE.Mesh
    ['25']: THREE.Mesh
    ['26']: THREE.Mesh
    ['27']: THREE.Mesh
    ['34']: THREE.Mesh
    ['34-1']: THREE.Mesh
    ['39']: THREE.Mesh
    ['4']: THREE.Mesh
    ['44']: THREE.Mesh
    ['45']: THREE.Mesh
    ['47']: THREE.Mesh
    ['5']: THREE.Mesh
    ['56']: THREE.Mesh
    ['60']: THREE.Mesh
    ['65']: THREE.Mesh
    ['65-1']: THREE.Mesh
    ['73']: THREE.Mesh
    ['77']: THREE.Mesh
    ['80']: THREE.Mesh
    ['81']: THREE.Mesh
    ['83']: THREE.Mesh
    ['86']: THREE.Mesh
    ['89']: THREE.Mesh
    ['93']: THREE.Mesh
    ['94']: THREE.Mesh
    ['97']: THREE.Mesh
    ['Mesh_#00']: THREE.Mesh
    ['Mesh_#00-1']: THREE.Mesh
    ['Mesh_#00-3']: THREE.Mesh
    ['Mesh_#01']: THREE.Mesh
    ['Mesh_#01-1']: THREE.Mesh
    ['Mesh_#01-3']: THREE.Mesh
    ['Mesh_#02']: THREE.Mesh
    ['Mesh_#02-1']: THREE.Mesh
    ['Mesh_#02-3']: THREE.Mesh
    ['Mesh_#03']: THREE.Mesh
    ['Mesh_#03-1']: THREE.Mesh
    ['Mesh_#03-3']: THREE.Mesh
    ['Mesh_#04']: THREE.Mesh
    ['Mesh_#04-1']: THREE.Mesh
    ['Mesh_#04-3']: THREE.Mesh
    ['Mesh_#05']: THREE.Mesh
    ['Mesh_#05-1']: THREE.Mesh
    ['Mesh_#05-3']: THREE.Mesh
    ['Mesh_#06']: THREE.Mesh
    ['Mesh_#06-1']: THREE.Mesh
    ['Mesh_#06-3']: THREE.Mesh
    ['Mesh_#07']: THREE.Mesh
    ['Mesh_#07-1']: THREE.Mesh
    ['Mesh_#07-3']: THREE.Mesh
    ['Mesh_#08']: THREE.Mesh
    ['Mesh_#08-1']: THREE.Mesh
    ['Mesh_#08-3']: THREE.Mesh
    ['Mesh_#09']: THREE.Mesh
    ['Mesh_#09-1']: THREE.Mesh
    ['Mesh_#09-3']: THREE.Mesh
    ['Mesh_#10']: THREE.Mesh
    ['Mesh_#10-1']: THREE.Mesh
    ['Mesh_#10-3']: THREE.Mesh
    ['Mesh_#100']: THREE.Mesh
    ['Mesh_#100-']: THREE.Mesh
    ['Mesh_#101']: THREE.Mesh
    ['Mesh_#101-']: THREE.Mesh
    ['Mesh_#102']: THREE.Mesh
    ['Mesh_#102-']: THREE.Mesh
    ['Mesh_#103']: THREE.Mesh
    ['Mesh_#103-']: THREE.Mesh
    ['Mesh_#104']: THREE.Mesh
    ['Mesh_#104-']: THREE.Mesh
    ['Mesh_#105']: THREE.Mesh
    ['Mesh_#105-']: THREE.Mesh
    ['Mesh_#106']: THREE.Mesh
    ['Mesh_#106-']: THREE.Mesh
    ['Mesh_#107']: THREE.Mesh
    ['Mesh_#107-']: THREE.Mesh
    ['Mesh_#108']: THREE.Mesh
    ['Mesh_#108-']: THREE.Mesh
    ['Mesh_#109']: THREE.Mesh
    ['Mesh_#109-']: THREE.Mesh
    ['Mesh_#11']: THREE.Mesh
    ['Mesh_#11-1']: THREE.Mesh
    ['Mesh_#11-3']: THREE.Mesh
    ['Mesh_#110']: THREE.Mesh
    ['Mesh_#110-']: THREE.Mesh
    ['Mesh_#111']: THREE.Mesh
    ['Mesh_#112']: THREE.Mesh
    ['Mesh_#113']: THREE.Mesh
    ['Mesh_#114']: THREE.Mesh
    ['Mesh_#115']: THREE.Mesh
    ['Mesh_#116']: THREE.Mesh
    ['Mesh_#117']: THREE.Mesh
    ['Mesh_#118']: THREE.Mesh
    ['Mesh_#119']: THREE.Mesh
    ['Mesh_#12']: THREE.Mesh
    ['Mesh_#12-1']: THREE.Mesh
    ['Mesh_#12-2']: THREE.Mesh
    ['Mesh_#13']: THREE.Mesh
    ['Mesh_#13-1']: THREE.Mesh
    ['Mesh_#13-2']: THREE.Mesh
    ['Mesh_#14']: THREE.Mesh
    ['Mesh_#14-1']: THREE.Mesh
    ['Mesh_#14-2']: THREE.Mesh
    ['Mesh_#15']: THREE.Mesh
    ['Mesh_#15-1']: THREE.Mesh
    ['Mesh_#15-2']: THREE.Mesh
    ['Mesh_#16']: THREE.Mesh
    ['Mesh_#16-1']: THREE.Mesh
    ['Mesh_#16-2']: THREE.Mesh
    ['Mesh_#17']: THREE.Mesh
    ['Mesh_#17-1']: THREE.Mesh
    ['Mesh_#17-2']: THREE.Mesh
    ['Mesh_#18']: THREE.Mesh
    ['Mesh_#18-1']: THREE.Mesh
    ['Mesh_#18-2']: THREE.Mesh
    ['Mesh_#19']: THREE.Mesh
    ['Mesh_#19-1']: THREE.Mesh
    ['Mesh_#19-2']: THREE.Mesh
    ['Mesh_#20']: THREE.Mesh
    ['Mesh_#20-1']: THREE.Mesh
    ['Mesh_#20-2']: THREE.Mesh
    ['Mesh_#21']: THREE.Mesh
    ['Mesh_#21-1']: THREE.Mesh
    ['Mesh_#21-2']: THREE.Mesh
    ['Mesh_#22']: THREE.Mesh
    ['Mesh_#22-1']: THREE.Mesh
    ['Mesh_#22-2']: THREE.Mesh
    ['Mesh_#23']: THREE.Mesh
    ['Mesh_#23-1']: THREE.Mesh
    ['Mesh_#23-2']: THREE.Mesh
    ['Mesh_#24']: THREE.Mesh
    ['Mesh_#24-1']: THREE.Mesh
    ['Mesh_#24-2']: THREE.Mesh
    ['Mesh_#25']: THREE.Mesh
    ['Mesh_#25-1']: THREE.Mesh
    ['Mesh_#26']: THREE.Mesh
    ['Mesh_#26-1']: THREE.Mesh
    ['Mesh_#27']: THREE.Mesh
    ['Mesh_#27-1']: THREE.Mesh
    ['Mesh_#27-2']: THREE.Mesh
    ['Mesh_#28']: THREE.Mesh
    ['Mesh_#28-1']: THREE.Mesh
    ['Mesh_#28-2']: THREE.Mesh
    ['Mesh_#29']: THREE.Mesh
    ['Mesh_#29-1']: THREE.Mesh
    ['Mesh_#29-2']: THREE.Mesh
    ['Mesh_#30']: THREE.Mesh
    ['Mesh_#30-1']: THREE.Mesh
    ['Mesh_#30-2']: THREE.Mesh
    ['Mesh_#31']: THREE.Mesh
    ['Mesh_#31-1']: THREE.Mesh
    ['Mesh_#31-2']: THREE.Mesh
    ['Mesh_#32']: THREE.Mesh
    ['Mesh_#32-1']: THREE.Mesh
    ['Mesh_#33']: THREE.Mesh
    ['Mesh_#33-1']: THREE.Mesh
    ['Mesh_#34']: THREE.Mesh
    ['Mesh_#34-1']: THREE.Mesh
    ['Mesh_#35']: THREE.Mesh
    ['Mesh_#35-1']: THREE.Mesh
    ['Mesh_#36']: THREE.Mesh
    ['Mesh_#36-1']: THREE.Mesh
    ['Mesh_#37']: THREE.Mesh
    ['Mesh_#37-1']: THREE.Mesh
    ['Mesh_#38']: THREE.Mesh
    ['Mesh_#38-1']: THREE.Mesh
    ['Mesh_#39']: THREE.Mesh
    ['Mesh_#39-1']: THREE.Mesh
    ['Mesh_#40']: THREE.Mesh
    ['Mesh_#40-1']: THREE.Mesh
    ['Mesh_#41']: THREE.Mesh
    ['Mesh_#41-1']: THREE.Mesh
    ['Mesh_#42']: THREE.Mesh
    ['Mesh_#42-1']: THREE.Mesh
    ['Mesh_#43']: THREE.Mesh
    ['Mesh_#43-1']: THREE.Mesh
    ['Mesh_#44']: THREE.Mesh
    ['Mesh_#44-1']: THREE.Mesh
    ['Mesh_#45']: THREE.Mesh
    ['Mesh_#45-1']: THREE.Mesh
    ['Mesh_#46']: THREE.Mesh
    ['Mesh_#46-1']: THREE.Mesh
    ['Mesh_#47']: THREE.Mesh
    ['Mesh_#47-1']: THREE.Mesh
    ['Mesh_#48']: THREE.Mesh
    ['Mesh_#48-1']: THREE.Mesh
    ['Mesh_#49']: THREE.Mesh
    ['Mesh_#49-1']: THREE.Mesh
    ['Mesh_#50']: THREE.Mesh
    ['Mesh_#50-1']: THREE.Mesh
    ['Mesh_#51']: THREE.Mesh
    ['Mesh_#51-1']: THREE.Mesh
    ['Mesh_#52']: THREE.Mesh
    ['Mesh_#52-1']: THREE.Mesh
    ['Mesh_#53']: THREE.Mesh
    ['Mesh_#53-1']: THREE.Mesh
    ['Mesh_#54']: THREE.Mesh
    ['Mesh_#54-1']: THREE.Mesh
    ['Mesh_#55']: THREE.Mesh
    ['Mesh_#55-1']: THREE.Mesh
    ['Mesh_#56']: THREE.Mesh
    ['Mesh_#56-1']: THREE.Mesh
    ['Mesh_#57']: THREE.Mesh
    ['Mesh_#57-1']: THREE.Mesh
    ['Mesh_#58']: THREE.Mesh
    ['Mesh_#58-1']: THREE.Mesh
    ['Mesh_#59']: THREE.Mesh
    ['Mesh_#59-1']: THREE.Mesh
    ['Mesh_#60']: THREE.Mesh
    ['Mesh_#60-1']: THREE.Mesh
    ['Mesh_#61']: THREE.Mesh
    ['Mesh_#61-1']: THREE.Mesh
    ['Mesh_#62']: THREE.Mesh
    ['Mesh_#62-1']: THREE.Mesh
    ['Mesh_#63']: THREE.Mesh
    ['Mesh_#63-1']: THREE.Mesh
    ['Mesh_#64']: THREE.Mesh
    ['Mesh_#64-1']: THREE.Mesh
    ['Mesh_#65']: THREE.Mesh
    ['Mesh_#65-1']: THREE.Mesh
    ['Mesh_#66']: THREE.Mesh
    ['Mesh_#66-1']: THREE.Mesh
    ['Mesh_#67']: THREE.Mesh
    ['Mesh_#67-1']: THREE.Mesh
    ['Mesh_#68']: THREE.Mesh
    ['Mesh_#68-1']: THREE.Mesh
    ['Mesh_#69']: THREE.Mesh
    ['Mesh_#69-1']: THREE.Mesh
    ['Mesh_#70']: THREE.Mesh
    ['Mesh_#70-1']: THREE.Mesh
    ['Mesh_#71']: THREE.Mesh
    ['Mesh_#71-1']: THREE.Mesh
    ['Mesh_#72']: THREE.Mesh
    ['Mesh_#72-1']: THREE.Mesh
    ['Mesh_#73']: THREE.Mesh
    ['Mesh_#73-1']: THREE.Mesh
    ['Mesh_#74']: THREE.Mesh
    ['Mesh_#74-1']: THREE.Mesh
    ['Mesh_#75']: THREE.Mesh
    ['Mesh_#75-1']: THREE.Mesh
    ['Mesh_#76']: THREE.Mesh
    ['Mesh_#76-1']: THREE.Mesh
    ['Mesh_#77']: THREE.Mesh
    ['Mesh_#77-1']: THREE.Mesh
    ['Mesh_#78']: THREE.Mesh
    ['Mesh_#78-1']: THREE.Mesh
    ['Mesh_#79']: THREE.Mesh
    ['Mesh_#79-1']: THREE.Mesh
    ['Mesh_#80']: THREE.Mesh
    ['Mesh_#80-1']: THREE.Mesh
    ['Mesh_#81']: THREE.Mesh
    ['Mesh_#81-1']: THREE.Mesh
    ['Mesh_#82']: THREE.Mesh
    ['Mesh_#82-1']: THREE.Mesh
    ['Mesh_#83']: THREE.Mesh
    ['Mesh_#83-1']: THREE.Mesh
    ['Mesh_#84']: THREE.Mesh
    ['Mesh_#84-1']: THREE.Mesh
    ['Mesh_#85']: THREE.Mesh
    ['Mesh_#85-1']: THREE.Mesh
    ['Mesh_#86']: THREE.Mesh
    ['Mesh_#86-1']: THREE.Mesh
    ['Mesh_#87']: THREE.Mesh
    ['Mesh_#87-1']: THREE.Mesh
    ['Mesh_#88']: THREE.Mesh
    ['Mesh_#88-1']: THREE.Mesh
    ['Mesh_#89']: THREE.Mesh
    ['Mesh_#89-1']: THREE.Mesh
    ['Mesh_#90']: THREE.Mesh
    ['Mesh_#90-1']: THREE.Mesh
    ['Mesh_#91']: THREE.Mesh
    ['Mesh_#91-1']: THREE.Mesh
    ['Mesh_#92']: THREE.Mesh
    ['Mesh_#92-1']: THREE.Mesh
    ['Mesh_#93']: THREE.Mesh
    ['Mesh_#93-1']: THREE.Mesh
    ['Mesh_#94']: THREE.Mesh
    ['Mesh_#94-1']: THREE.Mesh
    ['Mesh_#95']: THREE.Mesh
    ['Mesh_#95-1']: THREE.Mesh
    ['Mesh_#96']: THREE.Mesh
    ['Mesh_#96-1']: THREE.Mesh
    ['Mesh_#97']: THREE.Mesh
    ['Mesh_#97-1']: THREE.Mesh
    ['Mesh_#98']: THREE.Mesh
    ['Mesh_#98-1']: THREE.Mesh
    ['Mesh_#99']: THREE.Mesh
    ['Mesh_#99-1']: THREE.Mesh
  }
  materials: {
    ['0.001']: THREE.MeshStandardMaterial
    ['0-1.001']: THREE.MeshStandardMaterial
    ['10.001']: THREE.MeshStandardMaterial
    ['103.001']: THREE.MeshStandardMaterial
    ['104.001']: THREE.MeshStandardMaterial
    ['108.001']: THREE.MeshStandardMaterial
    ['11.001']: THREE.MeshStandardMaterial
    ['111.001']: THREE.MeshStandardMaterial
    ['112.001']: THREE.MeshStandardMaterial
    ['113.001']: THREE.MeshStandardMaterial
    ['116.001']: THREE.MeshStandardMaterial
    ['118.001']: THREE.MeshStandardMaterial
    ['119.001']: THREE.MeshStandardMaterial
    ['123.001']: THREE.MeshStandardMaterial
    ['13.001']: THREE.MeshStandardMaterial
    ['139.001']: THREE.MeshStandardMaterial
    ['14.001']: THREE.MeshStandardMaterial
    ['18.001']: THREE.MeshStandardMaterial
    ['19.001']: THREE.MeshStandardMaterial
    ['22.001']: THREE.MeshStandardMaterial
    ['25.001']: THREE.MeshStandardMaterial
    ['26.001']: THREE.MeshStandardMaterial
    ['27.001']: THREE.MeshStandardMaterial
    ['34.001']: THREE.MeshStandardMaterial
    ['34-1.001']: THREE.MeshStandardMaterial
    ['39.001']: THREE.MeshStandardMaterial
    ['4.001']: THREE.MeshStandardMaterial
    ['44.001']: THREE.MeshStandardMaterial
    ['45.001']: THREE.MeshStandardMaterial
    ['47.001']: THREE.MeshStandardMaterial
    ['5.001']: THREE.MeshStandardMaterial
    ['56.001']: THREE.MeshStandardMaterial
    ['60.001']: THREE.MeshStandardMaterial
    ['65.001']: THREE.MeshStandardMaterial
    ['65-1.001']: THREE.MeshStandardMaterial
    ['73.001']: THREE.MeshStandardMaterial
    ['77.001']: THREE.MeshStandardMaterial
    ['80.001']: THREE.MeshStandardMaterial
    ['81.001']: THREE.MeshStandardMaterial
    ['83.001']: THREE.MeshStandardMaterial
    ['86.001']: THREE.MeshStandardMaterial
    ['89.001']: THREE.MeshStandardMaterial
    ['93.001']: THREE.MeshStandardMaterial
    ['94.001']: THREE.MeshStandardMaterial
    ['97.001']: THREE.MeshStandardMaterial
    ['Mesh #00.001']: THREE.MeshStandardMaterial
    ['Mesh #00-1.001']: THREE.MeshStandardMaterial
    ['Mesh #00-3.001']: THREE.MeshStandardMaterial
    ['Mesh #01.001']: THREE.MeshStandardMaterial
    ['Mesh #01-1.001']: THREE.MeshStandardMaterial
    ['Mesh #01-3.001']: THREE.MeshStandardMaterial
    ['Mesh #02.001']: THREE.MeshStandardMaterial
    ['Mesh #02-1.001']: THREE.MeshStandardMaterial
    ['Mesh #02-3.001']: THREE.MeshStandardMaterial
    ['Mesh #03.001']: THREE.MeshStandardMaterial
    ['Mesh #03-1.001']: THREE.MeshStandardMaterial
    ['Mesh #03-3.001']: THREE.MeshStandardMaterial
    ['Mesh #04.001']: THREE.MeshStandardMaterial
    ['Mesh #04-1.001']: THREE.MeshStandardMaterial
    ['Mesh #04-3.001']: THREE.MeshStandardMaterial
    ['Mesh #05.001']: THREE.MeshStandardMaterial
    ['Mesh #05-1.001']: THREE.MeshStandardMaterial
    ['Mesh #05-3.001']: THREE.MeshStandardMaterial
    ['Mesh #06.001']: THREE.MeshStandardMaterial
    ['Mesh #06-1.001']: THREE.MeshStandardMaterial
    ['Mesh #06-3.001']: THREE.MeshStandardMaterial
    ['Mesh #07.001']: THREE.MeshStandardMaterial
    ['Mesh #07-1.001']: THREE.MeshStandardMaterial
    ['Mesh #07-3.001']: THREE.MeshStandardMaterial
    ['Mesh #08.001']: THREE.MeshStandardMaterial
    ['Mesh #08-1.001']: THREE.MeshStandardMaterial
    ['Mesh #08-3.001']: THREE.MeshStandardMaterial
    ['Mesh #09.001']: THREE.MeshStandardMaterial
    ['Mesh #09-1.001']: THREE.MeshStandardMaterial
    ['Mesh #09-3.001']: THREE.MeshStandardMaterial
    ['Mesh #10.001']: THREE.MeshStandardMaterial
    ['Mesh #10-1.001']: THREE.MeshStandardMaterial
    ['Mesh #10-3.001']: THREE.MeshStandardMaterial
    ['Mesh #100.001']: THREE.MeshStandardMaterial
    ['Mesh #100-1.001']: THREE.MeshStandardMaterial
    ['Mesh #101.001']: THREE.MeshStandardMaterial
    ['Mesh #101-1.001']: THREE.MeshStandardMaterial
    ['Mesh #102.001']: THREE.MeshStandardMaterial
    ['Mesh #102-1.001']: THREE.MeshStandardMaterial
    ['Mesh #103.001']: THREE.MeshStandardMaterial
    ['Mesh #103-1.001']: THREE.MeshStandardMaterial
    ['Mesh #104.001']: THREE.MeshStandardMaterial
    ['Mesh #104-1.001']: THREE.MeshStandardMaterial
    ['Mesh #105.001']: THREE.MeshStandardMaterial
    ['Mesh #105-1.001']: THREE.MeshStandardMaterial
    ['Mesh #106.001']: THREE.MeshStandardMaterial
    ['Mesh #106-1.001']: THREE.MeshStandardMaterial
    ['Mesh #107.001']: THREE.MeshStandardMaterial
    ['Mesh #107-1.001']: THREE.MeshStandardMaterial
    ['Mesh #108.001']: THREE.MeshStandardMaterial
    ['Mesh #108-1.001']: THREE.MeshStandardMaterial
    ['Mesh #109.001']: THREE.MeshStandardMaterial
    ['Mesh #109-1.001']: THREE.MeshStandardMaterial
    ['Mesh #11.001']: THREE.MeshStandardMaterial
    ['Mesh #11-1.001']: THREE.MeshStandardMaterial
    ['Mesh #11-3.001']: THREE.MeshStandardMaterial
    ['Mesh #110.001']: THREE.MeshStandardMaterial
    ['Mesh #110-1.001']: THREE.MeshStandardMaterial
    ['Mesh #111.001']: THREE.MeshStandardMaterial
    ['Mesh #112.001']: THREE.MeshStandardMaterial
    ['Mesh #113.001']: THREE.MeshStandardMaterial
    ['Mesh #114.001']: THREE.MeshStandardMaterial
    ['Mesh #115.001']: THREE.MeshStandardMaterial
    ['Mesh #116.001']: THREE.MeshStandardMaterial
    ['Mesh #117.001']: THREE.MeshStandardMaterial
    ['Mesh #118.001']: THREE.MeshStandardMaterial
    ['Mesh #119.001']: THREE.MeshStandardMaterial
    ['Mesh #12.001']: THREE.MeshStandardMaterial
    ['Mesh #12-1.001']: THREE.MeshStandardMaterial
    ['Mesh #12-2.001']: THREE.MeshStandardMaterial
    ['Mesh #13.001']: THREE.MeshStandardMaterial
    ['Mesh #13-1.001']: THREE.MeshStandardMaterial
    ['Mesh #13-2.001']: THREE.MeshStandardMaterial
    ['Mesh #14.001']: THREE.MeshStandardMaterial
    ['Mesh #14-1.001']: THREE.MeshStandardMaterial
    ['Mesh #14-2.001']: THREE.MeshStandardMaterial
    ['Mesh #15.001']: THREE.MeshStandardMaterial
    ['Mesh #15-1.001']: THREE.MeshStandardMaterial
    ['Mesh #15-2.001']: THREE.MeshStandardMaterial
    ['Mesh #16.001']: THREE.MeshStandardMaterial
    ['Mesh #16-1.001']: THREE.MeshStandardMaterial
    ['Mesh #16-2.001']: THREE.MeshStandardMaterial
    ['Mesh #17.001']: THREE.MeshStandardMaterial
    ['Mesh #17-1.001']: THREE.MeshStandardMaterial
    ['Mesh #17-2.001']: THREE.MeshStandardMaterial
    ['Mesh #18.001']: THREE.MeshStandardMaterial
    ['Mesh #18-1.001']: THREE.MeshStandardMaterial
    ['Mesh #18-2.001']: THREE.MeshStandardMaterial
    ['Mesh #19.001']: THREE.MeshStandardMaterial
    ['Mesh #19-1.001']: THREE.MeshStandardMaterial
    ['Mesh #19-2.001']: THREE.MeshStandardMaterial
    ['Mesh #20.001']: THREE.MeshStandardMaterial
    ['Mesh #20-1.001']: THREE.MeshStandardMaterial
    ['Mesh #20-2.001']: THREE.MeshStandardMaterial
    ['Mesh #21.001']: THREE.MeshStandardMaterial
    ['Mesh #21-1.001']: THREE.MeshStandardMaterial
    ['Mesh #21-2.001']: THREE.MeshStandardMaterial
    ['Mesh #22.001']: THREE.MeshStandardMaterial
    ['Mesh #22-1.001']: THREE.MeshStandardMaterial
    ['Mesh #22-2.001']: THREE.MeshStandardMaterial
    ['Mesh #23.001']: THREE.MeshStandardMaterial
    ['Mesh #23-1.001']: THREE.MeshStandardMaterial
    ['Mesh #23-2.001']: THREE.MeshStandardMaterial
    ['Mesh #24.001']: THREE.MeshStandardMaterial
    ['Mesh #24-1.001']: THREE.MeshStandardMaterial
    ['Mesh #24-2.001']: THREE.MeshStandardMaterial
    ['Mesh #25.001']: THREE.MeshStandardMaterial
    ['Mesh #25-1.001']: THREE.MeshStandardMaterial
    ['Mesh #26.001']: THREE.MeshStandardMaterial
    ['Mesh #26-1.001']: THREE.MeshStandardMaterial
    ['Mesh #27.001']: THREE.MeshStandardMaterial
    ['Mesh #27-1.001']: THREE.MeshStandardMaterial
    ['Mesh #27-2.001']: THREE.MeshStandardMaterial
    ['Mesh #28.001']: THREE.MeshStandardMaterial
    ['Mesh #28-1.001']: THREE.MeshStandardMaterial
    ['Mesh #28-2.001']: THREE.MeshStandardMaterial
    ['Mesh #29.001']: THREE.MeshStandardMaterial
    ['Mesh #29-1.001']: THREE.MeshStandardMaterial
    ['Mesh #29-2.001']: THREE.MeshStandardMaterial
    ['Mesh #30.001']: THREE.MeshStandardMaterial
    ['Mesh #30-1.001']: THREE.MeshStandardMaterial
    ['Mesh #30-2.001']: THREE.MeshStandardMaterial
    ['Mesh #31.001']: THREE.MeshStandardMaterial
    ['Mesh #31-1.001']: THREE.MeshStandardMaterial
    ['Mesh #31-2.001']: THREE.MeshStandardMaterial
    ['Mesh #32.001']: THREE.MeshStandardMaterial
    ['Mesh #32-1.001']: THREE.MeshStandardMaterial
    ['Mesh #33.001']: THREE.MeshStandardMaterial
    ['Mesh #33-1.001']: THREE.MeshStandardMaterial
    ['Mesh #34.001']: THREE.MeshStandardMaterial
    ['Mesh #34-1.001']: THREE.MeshStandardMaterial
    ['Mesh #35.001']: THREE.MeshStandardMaterial
    ['Mesh #35-1.001']: THREE.MeshStandardMaterial
    ['Mesh #36.001']: THREE.MeshStandardMaterial
    ['Mesh #36-1.001']: THREE.MeshStandardMaterial
    ['Mesh #37.001']: THREE.MeshStandardMaterial
    ['Mesh #37-1.001']: THREE.MeshStandardMaterial
    ['Mesh #38.001']: THREE.MeshStandardMaterial
    ['Mesh #38-1.001']: THREE.MeshStandardMaterial
    ['Mesh #39.001']: THREE.MeshStandardMaterial
    ['Mesh #39-1.001']: THREE.MeshStandardMaterial
    ['Mesh #40.001']: THREE.MeshStandardMaterial
    ['Mesh #40-1.001']: THREE.MeshStandardMaterial
    ['Mesh #41.001']: THREE.MeshStandardMaterial
    ['Mesh #41-1.001']: THREE.MeshStandardMaterial
    ['Mesh #42.001']: THREE.MeshStandardMaterial
    ['Mesh #42-1.001']: THREE.MeshStandardMaterial
    ['Mesh #43.001']: THREE.MeshStandardMaterial
    ['Mesh #43-1.001']: THREE.MeshStandardMaterial
    ['Mesh #44.001']: THREE.MeshStandardMaterial
    ['Mesh #44-1.001']: THREE.MeshStandardMaterial
    ['Mesh #45.001']: THREE.MeshStandardMaterial
    ['Mesh #45-1.001']: THREE.MeshStandardMaterial
    ['Mesh #46.001']: THREE.MeshStandardMaterial
    ['Mesh #46-1.001']: THREE.MeshStandardMaterial
    ['Mesh #47.001']: THREE.MeshStandardMaterial
    ['Mesh #47-1.001']: THREE.MeshStandardMaterial
    ['Mesh #48.001']: THREE.MeshStandardMaterial
    ['Mesh #48-1.001']: THREE.MeshStandardMaterial
    ['Mesh #49.001']: THREE.MeshStandardMaterial
    ['Mesh #49-1.001']: THREE.MeshStandardMaterial
    ['Mesh #50.001']: THREE.MeshStandardMaterial
    ['Mesh #50-1.001']: THREE.MeshStandardMaterial
    ['Mesh #51.001']: THREE.MeshStandardMaterial
    ['Mesh #51-1.001']: THREE.MeshStandardMaterial
    ['Mesh #52.001']: THREE.MeshStandardMaterial
    ['Mesh #52-1.001']: THREE.MeshStandardMaterial
    ['Mesh #53.001']: THREE.MeshStandardMaterial
    ['Mesh #53-1.001']: THREE.MeshStandardMaterial
    ['Mesh #54.001']: THREE.MeshStandardMaterial
    ['Mesh #54-1.001']: THREE.MeshStandardMaterial
    ['Mesh #55.001']: THREE.MeshStandardMaterial
    ['Mesh #55-1.001']: THREE.MeshStandardMaterial
    ['Mesh #56.001']: THREE.MeshStandardMaterial
    ['Mesh #56-1.001']: THREE.MeshStandardMaterial
    ['Mesh #57.001']: THREE.MeshStandardMaterial
    ['Mesh #57-1.001']: THREE.MeshStandardMaterial
    ['Mesh #58.001']: THREE.MeshStandardMaterial
    ['Mesh #58-1.001']: THREE.MeshStandardMaterial
    ['Mesh #59.001']: THREE.MeshStandardMaterial
    ['Mesh #59-1.001']: THREE.MeshStandardMaterial
    ['Mesh #60.001']: THREE.MeshStandardMaterial
    ['Mesh #60-1.001']: THREE.MeshStandardMaterial
    ['Mesh #61.001']: THREE.MeshStandardMaterial
    ['Mesh #61-1.001']: THREE.MeshStandardMaterial
    ['Mesh #62.001']: THREE.MeshStandardMaterial
    ['Mesh #62-1.001']: THREE.MeshStandardMaterial
    ['Mesh #63.001']: THREE.MeshStandardMaterial
    ['Mesh #63-1.001']: THREE.MeshStandardMaterial
    ['Mesh #64.001']: THREE.MeshStandardMaterial
    ['Mesh #64-1.001']: THREE.MeshStandardMaterial
    ['Mesh #65.001']: THREE.MeshStandardMaterial
    ['Mesh #65-1.001']: THREE.MeshStandardMaterial
    ['Mesh #66.001']: THREE.MeshStandardMaterial
    ['Mesh #66-1.001']: THREE.MeshStandardMaterial
    ['Mesh #67.001']: THREE.MeshStandardMaterial
    ['Mesh #67-1.001']: THREE.MeshStandardMaterial
    ['Mesh #68.001']: THREE.MeshStandardMaterial
    ['Mesh #68-1.001']: THREE.MeshStandardMaterial
    ['Mesh #69.001']: THREE.MeshStandardMaterial
    ['Mesh #69-1.001']: THREE.MeshStandardMaterial
    ['Mesh #70.001']: THREE.MeshStandardMaterial
    ['Mesh #70-1.001']: THREE.MeshStandardMaterial
    ['Mesh #71.001']: THREE.MeshStandardMaterial
    ['Mesh #71-1.001']: THREE.MeshStandardMaterial
    ['Mesh #72.001']: THREE.MeshStandardMaterial
    ['Mesh #72-1.001']: THREE.MeshStandardMaterial
    ['Mesh #73.001']: THREE.MeshStandardMaterial
    ['Mesh #73-1.001']: THREE.MeshStandardMaterial
    ['Mesh #74.001']: THREE.MeshStandardMaterial
    ['Mesh #74-1.001']: THREE.MeshStandardMaterial
    ['Mesh #75.001']: THREE.MeshStandardMaterial
    ['Mesh #75-1.001']: THREE.MeshStandardMaterial
    ['Mesh #76.001']: THREE.MeshStandardMaterial
    ['Mesh #76-1.001']: THREE.MeshStandardMaterial
    ['Mesh #77.001']: THREE.MeshStandardMaterial
    ['Mesh #77-1.001']: THREE.MeshStandardMaterial
    ['Mesh #78.001']: THREE.MeshStandardMaterial
    ['Mesh #78-1.001']: THREE.MeshStandardMaterial
    ['Mesh #79.001']: THREE.MeshStandardMaterial
    ['Mesh #79-1.001']: THREE.MeshStandardMaterial
    ['Mesh #80.001']: THREE.MeshStandardMaterial
    ['Mesh #80-1.001']: THREE.MeshStandardMaterial
    ['Mesh #81.001']: THREE.MeshStandardMaterial
    ['Mesh #81-1.001']: THREE.MeshStandardMaterial
    ['Mesh #82.001']: THREE.MeshStandardMaterial
    ['Mesh #82-1.001']: THREE.MeshStandardMaterial
    ['Mesh #83.001']: THREE.MeshStandardMaterial
    ['Mesh #83-1.001']: THREE.MeshStandardMaterial
    ['Mesh #84.001']: THREE.MeshStandardMaterial
    ['Mesh #84-1.001']: THREE.MeshStandardMaterial
    ['Mesh #85.001']: THREE.MeshStandardMaterial
    ['Mesh #85-1.001']: THREE.MeshStandardMaterial
    ['Mesh #86.001']: THREE.MeshStandardMaterial
    ['Mesh #86-1.001']: THREE.MeshStandardMaterial
    ['Mesh #87.001']: THREE.MeshStandardMaterial
    ['Mesh #87-1.001']: THREE.MeshStandardMaterial
    ['Mesh #88.001']: THREE.MeshStandardMaterial
    ['Mesh #88-1.001']: THREE.MeshStandardMaterial
    ['Mesh #89.001']: THREE.MeshStandardMaterial
    ['Mesh #89-1.001']: THREE.MeshStandardMaterial
    ['Mesh #90.001']: THREE.MeshStandardMaterial
    ['Mesh #90-1.001']: THREE.MeshStandardMaterial
    ['Mesh #91.001']: THREE.MeshStandardMaterial
    ['Mesh #91-1.001']: THREE.MeshStandardMaterial
    ['Mesh #92.001']: THREE.MeshStandardMaterial
    ['Mesh #92-1.001']: THREE.MeshStandardMaterial
    ['Mesh #93.001']: THREE.MeshStandardMaterial
    ['Mesh #93-1.001']: THREE.MeshStandardMaterial
    ['Mesh #94.001']: THREE.MeshStandardMaterial
    ['Mesh #94-1.001']: THREE.MeshStandardMaterial
    ['Mesh #95.001']: THREE.MeshStandardMaterial
    ['Mesh #95-1.001']: THREE.MeshStandardMaterial
    ['Mesh #96.001']: THREE.MeshStandardMaterial
    ['Mesh #96-1.001']: THREE.MeshStandardMaterial
    ['Mesh #97.001']: THREE.MeshStandardMaterial
    ['Mesh #97-1.001']: THREE.MeshStandardMaterial
    ['Mesh #98.001']: THREE.MeshStandardMaterial
    ['Mesh #98-1.001']: THREE.MeshStandardMaterial
    ['Mesh #99.001']: THREE.MeshStandardMaterial
    ['Mesh #99-1.001']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/../CassiniHuygensB.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['0'].geometry} material={materials['0.001']} />
      <mesh geometry={nodes['0-1'].geometry} material={materials['0-1.001']} />
      <mesh geometry={nodes['10'].geometry} material={materials['10.001']} />
      <mesh geometry={nodes['103'].geometry} material={materials['103.001']} />
      <mesh geometry={nodes['104'].geometry} material={materials['104.001']} />
      <mesh geometry={nodes['108'].geometry} material={materials['108.001']} />
      <mesh geometry={nodes['11'].geometry} material={materials['11.001']} />
      <mesh geometry={nodes['111'].geometry} material={materials['111.001']} />
      <mesh geometry={nodes['112'].geometry} material={materials['112.001']} />
      <mesh geometry={nodes['113'].geometry} material={materials['113.001']} />
      <mesh geometry={nodes['116'].geometry} material={materials['116.001']} />
      <mesh geometry={nodes['118'].geometry} material={materials['118.001']} />
      <mesh geometry={nodes['119'].geometry} material={materials['119.001']} />
      <mesh geometry={nodes['123'].geometry} material={materials['123.001']} />
      <mesh geometry={nodes['13'].geometry} material={materials['13.001']} />
      <mesh geometry={nodes['139'].geometry} material={materials['139.001']} />
      <mesh geometry={nodes['14'].geometry} material={materials['14.001']} />
      <mesh geometry={nodes['18'].geometry} material={materials['18.001']} />
      <mesh geometry={nodes['19'].geometry} material={materials['19.001']} />
      <mesh geometry={nodes['22'].geometry} material={materials['22.001']} />
      <mesh geometry={nodes['25'].geometry} material={materials['25.001']} />
      <mesh geometry={nodes['26'].geometry} material={materials['26.001']} />
      <mesh geometry={nodes['27'].geometry} material={materials['27.001']} />
      <mesh geometry={nodes['34'].geometry} material={materials['34.001']} />
      <mesh geometry={nodes['34-1'].geometry} material={materials['34-1.001']} />
      <mesh geometry={nodes['39'].geometry} material={materials['39.001']} />
      <mesh geometry={nodes['4'].geometry} material={materials['4.001']} />
      <mesh geometry={nodes['44'].geometry} material={materials['44.001']} />
      <mesh geometry={nodes['45'].geometry} material={materials['45.001']} />
      <mesh geometry={nodes['47'].geometry} material={materials['47.001']} />
      <mesh geometry={nodes['5'].geometry} material={materials['5.001']} />
      <mesh geometry={nodes['56'].geometry} material={materials['56.001']} />
      <mesh geometry={nodes['60'].geometry} material={materials['60.001']} />
      <mesh geometry={nodes['65'].geometry} material={materials['65.001']} />
      <mesh geometry={nodes['65-1'].geometry} material={materials['65-1.001']} />
      <mesh geometry={nodes['73'].geometry} material={materials['73.001']} />
      <mesh geometry={nodes['77'].geometry} material={materials['77.001']} />
      <mesh geometry={nodes['80'].geometry} material={materials['80.001']} />
      <mesh geometry={nodes['81'].geometry} material={materials['81.001']} />
      <mesh geometry={nodes['83'].geometry} material={materials['83.001']} />
      <mesh geometry={nodes['86'].geometry} material={materials['86.001']} />
      <mesh geometry={nodes['89'].geometry} material={materials['89.001']} />
      <mesh geometry={nodes['93'].geometry} material={materials['93.001']} />
      <mesh geometry={nodes['94'].geometry} material={materials['94.001']} />
      <mesh geometry={nodes['97'].geometry} material={materials['97.001']} />
      <mesh geometry={nodes['Mesh_#00'].geometry} material={materials['Mesh #00.001']} />
      <mesh geometry={nodes['Mesh_#00-1'].geometry} material={materials['Mesh #00-1.001']} />
      <mesh geometry={nodes['Mesh_#00-3'].geometry} material={materials['Mesh #00-3.001']} />
      <mesh geometry={nodes['Mesh_#01'].geometry} material={materials['Mesh #01.001']} />
      <mesh geometry={nodes['Mesh_#01-1'].geometry} material={materials['Mesh #01-1.001']} />
      <mesh geometry={nodes['Mesh_#01-3'].geometry} material={materials['Mesh #01-3.001']} />
      <mesh geometry={nodes['Mesh_#02'].geometry} material={materials['Mesh #02.001']} />
      <mesh geometry={nodes['Mesh_#02-1'].geometry} material={materials['Mesh #02-1.001']} />
      <mesh geometry={nodes['Mesh_#02-3'].geometry} material={materials['Mesh #02-3.001']} />
      <mesh geometry={nodes['Mesh_#03'].geometry} material={materials['Mesh #03.001']} />
      <mesh geometry={nodes['Mesh_#03-1'].geometry} material={materials['Mesh #03-1.001']} />
      <mesh geometry={nodes['Mesh_#03-3'].geometry} material={materials['Mesh #03-3.001']} />
      <mesh geometry={nodes['Mesh_#04'].geometry} material={materials['Mesh #04.001']} />
      <mesh geometry={nodes['Mesh_#04-1'].geometry} material={materials['Mesh #04-1.001']} />
      <mesh geometry={nodes['Mesh_#04-3'].geometry} material={materials['Mesh #04-3.001']} />
      <mesh geometry={nodes['Mesh_#05'].geometry} material={materials['Mesh #05.001']} />
      <mesh geometry={nodes['Mesh_#05-1'].geometry} material={materials['Mesh #05-1.001']} />
      <mesh geometry={nodes['Mesh_#05-3'].geometry} material={materials['Mesh #05-3.001']} />
      <mesh geometry={nodes['Mesh_#06'].geometry} material={materials['Mesh #06.001']} />
      <mesh geometry={nodes['Mesh_#06-1'].geometry} material={materials['Mesh #06-1.001']} />
      <mesh geometry={nodes['Mesh_#06-3'].geometry} material={materials['Mesh #06-3.001']} />
      <mesh geometry={nodes['Mesh_#07'].geometry} material={materials['Mesh #07.001']} />
      <mesh geometry={nodes['Mesh_#07-1'].geometry} material={materials['Mesh #07-1.001']} />
      <mesh geometry={nodes['Mesh_#07-3'].geometry} material={materials['Mesh #07-3.001']} />
      <mesh geometry={nodes['Mesh_#08'].geometry} material={materials['Mesh #08.001']} />
      <mesh geometry={nodes['Mesh_#08-1'].geometry} material={materials['Mesh #08-1.001']} />
      <mesh geometry={nodes['Mesh_#08-3'].geometry} material={materials['Mesh #08-3.001']} />
      <mesh geometry={nodes['Mesh_#09'].geometry} material={materials['Mesh #09.001']} />
      <mesh geometry={nodes['Mesh_#09-1'].geometry} material={materials['Mesh #09-1.001']} />
      <mesh geometry={nodes['Mesh_#09-3'].geometry} material={materials['Mesh #09-3.001']} />
      <mesh geometry={nodes['Mesh_#10'].geometry} material={materials['Mesh #10.001']} />
      <mesh geometry={nodes['Mesh_#10-1'].geometry} material={materials['Mesh #10-1.001']} />
      <mesh geometry={nodes['Mesh_#10-3'].geometry} material={materials['Mesh #10-3.001']} />
      <mesh geometry={nodes['Mesh_#100'].geometry} material={materials['Mesh #100.001']} />
      <mesh geometry={nodes['Mesh_#100-'].geometry} material={materials['Mesh #100-1.001']} />
      <mesh geometry={nodes['Mesh_#101'].geometry} material={materials['Mesh #101.001']} />
      <mesh geometry={nodes['Mesh_#101-'].geometry} material={materials['Mesh #101-1.001']} />
      <mesh geometry={nodes['Mesh_#102'].geometry} material={materials['Mesh #102.001']} />
      <mesh geometry={nodes['Mesh_#102-'].geometry} material={materials['Mesh #102-1.001']} />
      <mesh geometry={nodes['Mesh_#103'].geometry} material={materials['Mesh #103.001']} />
      <mesh geometry={nodes['Mesh_#103-'].geometry} material={materials['Mesh #103-1.001']} />
      <mesh geometry={nodes['Mesh_#104'].geometry} material={materials['Mesh #104.001']} />
      <mesh geometry={nodes['Mesh_#104-'].geometry} material={materials['Mesh #104-1.001']} />
      <mesh geometry={nodes['Mesh_#105'].geometry} material={materials['Mesh #105.001']} />
      <mesh geometry={nodes['Mesh_#105-'].geometry} material={materials['Mesh #105-1.001']} />
      <mesh geometry={nodes['Mesh_#106'].geometry} material={materials['Mesh #106.001']} />
      <mesh geometry={nodes['Mesh_#106-'].geometry} material={materials['Mesh #106-1.001']} />
      <mesh geometry={nodes['Mesh_#107'].geometry} material={materials['Mesh #107.001']} />
      <mesh geometry={nodes['Mesh_#107-'].geometry} material={materials['Mesh #107-1.001']} />
      <mesh geometry={nodes['Mesh_#108'].geometry} material={materials['Mesh #108.001']} />
      <mesh geometry={nodes['Mesh_#108-'].geometry} material={materials['Mesh #108-1.001']} />
      <mesh geometry={nodes['Mesh_#109'].geometry} material={materials['Mesh #109.001']} />
      <mesh geometry={nodes['Mesh_#109-'].geometry} material={materials['Mesh #109-1.001']} />
      <mesh geometry={nodes['Mesh_#11'].geometry} material={materials['Mesh #11.001']} />
      <mesh geometry={nodes['Mesh_#11-1'].geometry} material={materials['Mesh #11-1.001']} />
      <mesh geometry={nodes['Mesh_#11-3'].geometry} material={materials['Mesh #11-3.001']} />
      <mesh geometry={nodes['Mesh_#110'].geometry} material={materials['Mesh #110.001']} />
      <mesh geometry={nodes['Mesh_#110-'].geometry} material={materials['Mesh #110-1.001']} />
      <mesh geometry={nodes['Mesh_#111'].geometry} material={materials['Mesh #111.001']} />
      <mesh geometry={nodes['Mesh_#112'].geometry} material={materials['Mesh #112.001']} />
      <mesh geometry={nodes['Mesh_#113'].geometry} material={materials['Mesh #113.001']} />
      <mesh geometry={nodes['Mesh_#114'].geometry} material={materials['Mesh #114.001']} />
      <mesh geometry={nodes['Mesh_#115'].geometry} material={materials['Mesh #115.001']} />
      <mesh geometry={nodes['Mesh_#116'].geometry} material={materials['Mesh #116.001']} />
      <mesh geometry={nodes['Mesh_#117'].geometry} material={materials['Mesh #117.001']} />
      <mesh geometry={nodes['Mesh_#118'].geometry} material={materials['Mesh #118.001']} />
      <mesh geometry={nodes['Mesh_#119'].geometry} material={materials['Mesh #119.001']} />
      <mesh geometry={nodes['Mesh_#12'].geometry} material={materials['Mesh #12.001']} />
      <mesh geometry={nodes['Mesh_#12-1'].geometry} material={materials['Mesh #12-1.001']} />
      <mesh geometry={nodes['Mesh_#12-2'].geometry} material={materials['Mesh #12-2.001']} />
      <mesh geometry={nodes['Mesh_#13'].geometry} material={materials['Mesh #13.001']} />
      <mesh geometry={nodes['Mesh_#13-1'].geometry} material={materials['Mesh #13-1.001']} />
      <mesh geometry={nodes['Mesh_#13-2'].geometry} material={materials['Mesh #13-2.001']} />
      <mesh geometry={nodes['Mesh_#14'].geometry} material={materials['Mesh #14.001']} />
      <mesh geometry={nodes['Mesh_#14-1'].geometry} material={materials['Mesh #14-1.001']} />
      <mesh geometry={nodes['Mesh_#14-2'].geometry} material={materials['Mesh #14-2.001']} />
      <mesh geometry={nodes['Mesh_#15'].geometry} material={materials['Mesh #15.001']} />
      <mesh geometry={nodes['Mesh_#15-1'].geometry} material={materials['Mesh #15-1.001']} />
      <mesh geometry={nodes['Mesh_#15-2'].geometry} material={materials['Mesh #15-2.001']} />
      <mesh geometry={nodes['Mesh_#16'].geometry} material={materials['Mesh #16.001']} />
      <mesh geometry={nodes['Mesh_#16-1'].geometry} material={materials['Mesh #16-1.001']} />
      <mesh geometry={nodes['Mesh_#16-2'].geometry} material={materials['Mesh #16-2.001']} />
      <mesh geometry={nodes['Mesh_#17'].geometry} material={materials['Mesh #17.001']} />
      <mesh geometry={nodes['Mesh_#17-1'].geometry} material={materials['Mesh #17-1.001']} />
      <mesh geometry={nodes['Mesh_#17-2'].geometry} material={materials['Mesh #17-2.001']} />
      <mesh geometry={nodes['Mesh_#18'].geometry} material={materials['Mesh #18.001']} />
      <mesh geometry={nodes['Mesh_#18-1'].geometry} material={materials['Mesh #18-1.001']} />
      <mesh geometry={nodes['Mesh_#18-2'].geometry} material={materials['Mesh #18-2.001']} />
      <mesh geometry={nodes['Mesh_#19'].geometry} material={materials['Mesh #19.001']} />
      <mesh geometry={nodes['Mesh_#19-1'].geometry} material={materials['Mesh #19-1.001']} />
      <mesh geometry={nodes['Mesh_#19-2'].geometry} material={materials['Mesh #19-2.001']} />
      <mesh geometry={nodes['Mesh_#20'].geometry} material={materials['Mesh #20.001']} />
      <mesh geometry={nodes['Mesh_#20-1'].geometry} material={materials['Mesh #20-1.001']} />
      <mesh geometry={nodes['Mesh_#20-2'].geometry} material={materials['Mesh #20-2.001']} />
      <mesh geometry={nodes['Mesh_#21'].geometry} material={materials['Mesh #21.001']} />
      <mesh geometry={nodes['Mesh_#21-1'].geometry} material={materials['Mesh #21-1.001']} />
      <mesh geometry={nodes['Mesh_#21-2'].geometry} material={materials['Mesh #21-2.001']} />
      <mesh geometry={nodes['Mesh_#22'].geometry} material={materials['Mesh #22.001']} />
      <mesh geometry={nodes['Mesh_#22-1'].geometry} material={materials['Mesh #22-1.001']} />
      <mesh geometry={nodes['Mesh_#22-2'].geometry} material={materials['Mesh #22-2.001']} />
      <mesh geometry={nodes['Mesh_#23'].geometry} material={materials['Mesh #23.001']} />
      <mesh geometry={nodes['Mesh_#23-1'].geometry} material={materials['Mesh #23-1.001']} />
      <mesh geometry={nodes['Mesh_#23-2'].geometry} material={materials['Mesh #23-2.001']} />
      <mesh geometry={nodes['Mesh_#24'].geometry} material={materials['Mesh #24.001']} />
      <mesh geometry={nodes['Mesh_#24-1'].geometry} material={materials['Mesh #24-1.001']} />
      <mesh geometry={nodes['Mesh_#24-2'].geometry} material={materials['Mesh #24-2.001']} />
      <mesh geometry={nodes['Mesh_#25'].geometry} material={materials['Mesh #25.001']} />
      <mesh geometry={nodes['Mesh_#25-1'].geometry} material={materials['Mesh #25-1.001']} />
      <mesh geometry={nodes['Mesh_#26'].geometry} material={materials['Mesh #26.001']} />
      <mesh geometry={nodes['Mesh_#26-1'].geometry} material={materials['Mesh #26-1.001']} />
      <mesh geometry={nodes['Mesh_#27'].geometry} material={materials['Mesh #27.001']} />
      <mesh geometry={nodes['Mesh_#27-1'].geometry} material={materials['Mesh #27-1.001']} />
      <mesh geometry={nodes['Mesh_#27-2'].geometry} material={materials['Mesh #27-2.001']} />
      <mesh geometry={nodes['Mesh_#28'].geometry} material={materials['Mesh #28.001']} />
      <mesh geometry={nodes['Mesh_#28-1'].geometry} material={materials['Mesh #28-1.001']} />
      <mesh geometry={nodes['Mesh_#28-2'].geometry} material={materials['Mesh #28-2.001']} />
      <mesh geometry={nodes['Mesh_#29'].geometry} material={materials['Mesh #29.001']} />
      <mesh geometry={nodes['Mesh_#29-1'].geometry} material={materials['Mesh #29-1.001']} />
      <mesh geometry={nodes['Mesh_#29-2'].geometry} material={materials['Mesh #29-2.001']} />
      <mesh geometry={nodes['Mesh_#30'].geometry} material={materials['Mesh #30.001']} />
      <mesh geometry={nodes['Mesh_#30-1'].geometry} material={materials['Mesh #30-1.001']} />
      <mesh geometry={nodes['Mesh_#30-2'].geometry} material={materials['Mesh #30-2.001']} />
      <mesh geometry={nodes['Mesh_#31'].geometry} material={materials['Mesh #31.001']} />
      <mesh geometry={nodes['Mesh_#31-1'].geometry} material={materials['Mesh #31-1.001']} />
      <mesh geometry={nodes['Mesh_#31-2'].geometry} material={materials['Mesh #31-2.001']} />
      <mesh geometry={nodes['Mesh_#32'].geometry} material={materials['Mesh #32.001']} />
      <mesh geometry={nodes['Mesh_#32-1'].geometry} material={materials['Mesh #32-1.001']} />
      <mesh geometry={nodes['Mesh_#33'].geometry} material={materials['Mesh #33.001']} />
      <mesh geometry={nodes['Mesh_#33-1'].geometry} material={materials['Mesh #33-1.001']} />
      <mesh geometry={nodes['Mesh_#34'].geometry} material={materials['Mesh #34.001']} />
      <mesh geometry={nodes['Mesh_#34-1'].geometry} material={materials['Mesh #34-1.001']} />
      <mesh geometry={nodes['Mesh_#35'].geometry} material={materials['Mesh #35.001']} />
      <mesh geometry={nodes['Mesh_#35-1'].geometry} material={materials['Mesh #35-1.001']} />
      <mesh geometry={nodes['Mesh_#36'].geometry} material={materials['Mesh #36.001']} />
      <mesh geometry={nodes['Mesh_#36-1'].geometry} material={materials['Mesh #36-1.001']} />
      <mesh geometry={nodes['Mesh_#37'].geometry} material={materials['Mesh #37.001']} />
      <mesh geometry={nodes['Mesh_#37-1'].geometry} material={materials['Mesh #37-1.001']} />
      <mesh geometry={nodes['Mesh_#38'].geometry} material={materials['Mesh #38.001']} />
      <mesh geometry={nodes['Mesh_#38-1'].geometry} material={materials['Mesh #38-1.001']} />
      <mesh geometry={nodes['Mesh_#39'].geometry} material={materials['Mesh #39.001']} />
      <mesh geometry={nodes['Mesh_#39-1'].geometry} material={materials['Mesh #39-1.001']} />
      <mesh geometry={nodes['Mesh_#40'].geometry} material={materials['Mesh #40.001']} />
      <mesh geometry={nodes['Mesh_#40-1'].geometry} material={materials['Mesh #40-1.001']} />
      <mesh geometry={nodes['Mesh_#41'].geometry} material={materials['Mesh #41.001']} />
      <mesh geometry={nodes['Mesh_#41-1'].geometry} material={materials['Mesh #41-1.001']} />
      <mesh geometry={nodes['Mesh_#42'].geometry} material={materials['Mesh #42.001']} />
      <mesh geometry={nodes['Mesh_#42-1'].geometry} material={materials['Mesh #42-1.001']} />
      <mesh geometry={nodes['Mesh_#43'].geometry} material={materials['Mesh #43.001']} />
      <mesh geometry={nodes['Mesh_#43-1'].geometry} material={materials['Mesh #43-1.001']} />
      <mesh geometry={nodes['Mesh_#44'].geometry} material={materials['Mesh #44.001']} />
      <mesh geometry={nodes['Mesh_#44-1'].geometry} material={materials['Mesh #44-1.001']} />
      <mesh geometry={nodes['Mesh_#45'].geometry} material={materials['Mesh #45.001']} />
      <mesh geometry={nodes['Mesh_#45-1'].geometry} material={materials['Mesh #45-1.001']} />
      <mesh geometry={nodes['Mesh_#46'].geometry} material={materials['Mesh #46.001']} />
      <mesh geometry={nodes['Mesh_#46-1'].geometry} material={materials['Mesh #46-1.001']} />
      <mesh geometry={nodes['Mesh_#47'].geometry} material={materials['Mesh #47.001']} />
      <mesh geometry={nodes['Mesh_#47-1'].geometry} material={materials['Mesh #47-1.001']} />
      <mesh geometry={nodes['Mesh_#48'].geometry} material={materials['Mesh #48.001']} />
      <mesh geometry={nodes['Mesh_#48-1'].geometry} material={materials['Mesh #48-1.001']} />
      <mesh geometry={nodes['Mesh_#49'].geometry} material={materials['Mesh #49.001']} />
      <mesh geometry={nodes['Mesh_#49-1'].geometry} material={materials['Mesh #49-1.001']} />
      <mesh geometry={nodes['Mesh_#50'].geometry} material={materials['Mesh #50.001']} />
      <mesh geometry={nodes['Mesh_#50-1'].geometry} material={materials['Mesh #50-1.001']} />
      <mesh geometry={nodes['Mesh_#51'].geometry} material={materials['Mesh #51.001']} />
      <mesh geometry={nodes['Mesh_#51-1'].geometry} material={materials['Mesh #51-1.001']} />
      <mesh geometry={nodes['Mesh_#52'].geometry} material={materials['Mesh #52.001']} />
      <mesh geometry={nodes['Mesh_#52-1'].geometry} material={materials['Mesh #52-1.001']} />
      <mesh geometry={nodes['Mesh_#53'].geometry} material={materials['Mesh #53.001']} />
      <mesh geometry={nodes['Mesh_#53-1'].geometry} material={materials['Mesh #53-1.001']} />
      <mesh geometry={nodes['Mesh_#54'].geometry} material={materials['Mesh #54.001']} />
      <mesh geometry={nodes['Mesh_#54-1'].geometry} material={materials['Mesh #54-1.001']} />
      <mesh geometry={nodes['Mesh_#55'].geometry} material={materials['Mesh #55.001']} />
      <mesh geometry={nodes['Mesh_#55-1'].geometry} material={materials['Mesh #55-1.001']} />
      <mesh geometry={nodes['Mesh_#56'].geometry} material={materials['Mesh #56.001']} />
      <mesh geometry={nodes['Mesh_#56-1'].geometry} material={materials['Mesh #56-1.001']} />
      <mesh geometry={nodes['Mesh_#57'].geometry} material={materials['Mesh #57.001']} />
      <mesh geometry={nodes['Mesh_#57-1'].geometry} material={materials['Mesh #57-1.001']} />
      <mesh geometry={nodes['Mesh_#58'].geometry} material={materials['Mesh #58.001']} />
      <mesh geometry={nodes['Mesh_#58-1'].geometry} material={materials['Mesh #58-1.001']} />
      <mesh geometry={nodes['Mesh_#59'].geometry} material={materials['Mesh #59.001']} />
      <mesh geometry={nodes['Mesh_#59-1'].geometry} material={materials['Mesh #59-1.001']} />
      <mesh geometry={nodes['Mesh_#60'].geometry} material={materials['Mesh #60.001']} />
      <mesh geometry={nodes['Mesh_#60-1'].geometry} material={materials['Mesh #60-1.001']} />
      <mesh geometry={nodes['Mesh_#61'].geometry} material={materials['Mesh #61.001']} />
      <mesh geometry={nodes['Mesh_#61-1'].geometry} material={materials['Mesh #61-1.001']} />
      <mesh geometry={nodes['Mesh_#62'].geometry} material={materials['Mesh #62.001']} />
      <mesh geometry={nodes['Mesh_#62-1'].geometry} material={materials['Mesh #62-1.001']} />
      <mesh geometry={nodes['Mesh_#63'].geometry} material={materials['Mesh #63.001']} />
      <mesh geometry={nodes['Mesh_#63-1'].geometry} material={materials['Mesh #63-1.001']} />
      <mesh geometry={nodes['Mesh_#64'].geometry} material={materials['Mesh #64.001']} />
      <mesh geometry={nodes['Mesh_#64-1'].geometry} material={materials['Mesh #64-1.001']} />
      <mesh geometry={nodes['Mesh_#65'].geometry} material={materials['Mesh #65.001']} />
      <mesh geometry={nodes['Mesh_#65-1'].geometry} material={materials['Mesh #65-1.001']} />
      <mesh geometry={nodes['Mesh_#66'].geometry} material={materials['Mesh #66.001']} />
      <mesh geometry={nodes['Mesh_#66-1'].geometry} material={materials['Mesh #66-1.001']} />
      <mesh geometry={nodes['Mesh_#67'].geometry} material={materials['Mesh #67.001']} />
      <mesh geometry={nodes['Mesh_#67-1'].geometry} material={materials['Mesh #67-1.001']} />
      <mesh geometry={nodes['Mesh_#68'].geometry} material={materials['Mesh #68.001']} />
      <mesh geometry={nodes['Mesh_#68-1'].geometry} material={materials['Mesh #68-1.001']} />
      <mesh geometry={nodes['Mesh_#69'].geometry} material={materials['Mesh #69.001']} />
      <mesh geometry={nodes['Mesh_#69-1'].geometry} material={materials['Mesh #69-1.001']} />
      <mesh geometry={nodes['Mesh_#70'].geometry} material={materials['Mesh #70.001']} />
      <mesh geometry={nodes['Mesh_#70-1'].geometry} material={materials['Mesh #70-1.001']} />
      <mesh geometry={nodes['Mesh_#71'].geometry} material={materials['Mesh #71.001']} />
      <mesh geometry={nodes['Mesh_#71-1'].geometry} material={materials['Mesh #71-1.001']} />
      <mesh geometry={nodes['Mesh_#72'].geometry} material={materials['Mesh #72.001']} />
      <mesh geometry={nodes['Mesh_#72-1'].geometry} material={materials['Mesh #72-1.001']} />
      <mesh geometry={nodes['Mesh_#73'].geometry} material={materials['Mesh #73.001']} />
      <mesh geometry={nodes['Mesh_#73-1'].geometry} material={materials['Mesh #73-1.001']} />
      <mesh geometry={nodes['Mesh_#74'].geometry} material={materials['Mesh #74.001']} />
      <mesh geometry={nodes['Mesh_#74-1'].geometry} material={materials['Mesh #74-1.001']} />
      <mesh geometry={nodes['Mesh_#75'].geometry} material={materials['Mesh #75.001']} />
      <mesh geometry={nodes['Mesh_#75-1'].geometry} material={materials['Mesh #75-1.001']} />
      <mesh geometry={nodes['Mesh_#76'].geometry} material={materials['Mesh #76.001']} />
      <mesh geometry={nodes['Mesh_#76-1'].geometry} material={materials['Mesh #76-1.001']} />
      <mesh geometry={nodes['Mesh_#77'].geometry} material={materials['Mesh #77.001']} />
      <mesh geometry={nodes['Mesh_#77-1'].geometry} material={materials['Mesh #77-1.001']} />
      <mesh geometry={nodes['Mesh_#78'].geometry} material={materials['Mesh #78.001']} />
      <mesh geometry={nodes['Mesh_#78-1'].geometry} material={materials['Mesh #78-1.001']} />
      <mesh geometry={nodes['Mesh_#79'].geometry} material={materials['Mesh #79.001']} />
      <mesh geometry={nodes['Mesh_#79-1'].geometry} material={materials['Mesh #79-1.001']} />
      <mesh geometry={nodes['Mesh_#80'].geometry} material={materials['Mesh #80.001']} />
      <mesh geometry={nodes['Mesh_#80-1'].geometry} material={materials['Mesh #80-1.001']} />
      <mesh geometry={nodes['Mesh_#81'].geometry} material={materials['Mesh #81.001']} />
      <mesh geometry={nodes['Mesh_#81-1'].geometry} material={materials['Mesh #81-1.001']} />
      <mesh geometry={nodes['Mesh_#82'].geometry} material={materials['Mesh #82.001']} />
      <mesh geometry={nodes['Mesh_#82-1'].geometry} material={materials['Mesh #82-1.001']} />
      <mesh geometry={nodes['Mesh_#83'].geometry} material={materials['Mesh #83.001']} />
      <mesh geometry={nodes['Mesh_#83-1'].geometry} material={materials['Mesh #83-1.001']} />
      <mesh geometry={nodes['Mesh_#84'].geometry} material={materials['Mesh #84.001']} />
      <mesh geometry={nodes['Mesh_#84-1'].geometry} material={materials['Mesh #84-1.001']} />
      <mesh geometry={nodes['Mesh_#85'].geometry} material={materials['Mesh #85.001']} />
      <mesh geometry={nodes['Mesh_#85-1'].geometry} material={materials['Mesh #85-1.001']} />
      <mesh geometry={nodes['Mesh_#86'].geometry} material={materials['Mesh #86.001']} />
      <mesh geometry={nodes['Mesh_#86-1'].geometry} material={materials['Mesh #86-1.001']} />
      <mesh geometry={nodes['Mesh_#87'].geometry} material={materials['Mesh #87.001']} />
      <mesh geometry={nodes['Mesh_#87-1'].geometry} material={materials['Mesh #87-1.001']} />
      <mesh geometry={nodes['Mesh_#88'].geometry} material={materials['Mesh #88.001']} />
      <mesh geometry={nodes['Mesh_#88-1'].geometry} material={materials['Mesh #88-1.001']} />
      <mesh geometry={nodes['Mesh_#89'].geometry} material={materials['Mesh #89.001']} />
      <mesh geometry={nodes['Mesh_#89-1'].geometry} material={materials['Mesh #89-1.001']} />
      <mesh geometry={nodes['Mesh_#90'].geometry} material={materials['Mesh #90.001']} />
      <mesh geometry={nodes['Mesh_#90-1'].geometry} material={materials['Mesh #90-1.001']} />
      <mesh geometry={nodes['Mesh_#91'].geometry} material={materials['Mesh #91.001']} />
      <mesh geometry={nodes['Mesh_#91-1'].geometry} material={materials['Mesh #91-1.001']} />
      <mesh geometry={nodes['Mesh_#92'].geometry} material={materials['Mesh #92.001']} />
      <mesh geometry={nodes['Mesh_#92-1'].geometry} material={materials['Mesh #92-1.001']} />
      <mesh geometry={nodes['Mesh_#93'].geometry} material={materials['Mesh #93.001']} />
      <mesh geometry={nodes['Mesh_#93-1'].geometry} material={materials['Mesh #93-1.001']} />
      <mesh geometry={nodes['Mesh_#94'].geometry} material={materials['Mesh #94.001']} />
      <mesh geometry={nodes['Mesh_#94-1'].geometry} material={materials['Mesh #94-1.001']} />
      <mesh geometry={nodes['Mesh_#95'].geometry} material={materials['Mesh #95.001']} />
      <mesh geometry={nodes['Mesh_#95-1'].geometry} material={materials['Mesh #95-1.001']} />
      <mesh geometry={nodes['Mesh_#96'].geometry} material={materials['Mesh #96.001']} />
      <mesh geometry={nodes['Mesh_#96-1'].geometry} material={materials['Mesh #96-1.001']} />
      <mesh geometry={nodes['Mesh_#97'].geometry} material={materials['Mesh #97.001']} />
      <mesh geometry={nodes['Mesh_#97-1'].geometry} material={materials['Mesh #97-1.001']} />
      <mesh geometry={nodes['Mesh_#98'].geometry} material={materials['Mesh #98.001']} />
      <mesh geometry={nodes['Mesh_#98-1'].geometry} material={materials['Mesh #98-1.001']} />
      <mesh geometry={nodes['Mesh_#99'].geometry} material={materials['Mesh #99.001']} />
      <mesh geometry={nodes['Mesh_#99-1'].geometry} material={materials['Mesh #99-1.001']} />
    </group>
  )
}

useGLTF.preload('/../CassiniHuygensB.glb')
