/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CassiniHuygensAwithout_Cassini.glb -t -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    _root: THREE.Mesh
    foil_gold_h: THREE.Mesh
    tex_01_h: THREE.Mesh
  }
  materials: {
    foil_gold: THREE.MeshStandardMaterial
    tex_01: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/../CassiniHuygensAwithout_Cassini.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._root.geometry} material={nodes._root.material}>
        <mesh geometry={nodes.foil_gold_h.geometry} material={materials.foil_gold} position={[0.025, 0, 0]} scale={0.5} />
        <mesh geometry={nodes.tex_01_h.geometry} material={materials.tex_01} position={[0.309, -0.382, 0]} scale={0.5} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/../CassiniHuygensAwithout_Cassini.glb')
