/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CassiniHuygensAwithoutHyugens.glb -t -r public 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    _root: THREE.Mesh
    aluminum: THREE.Mesh
    black_krinkle: THREE.Mesh
    dish: THREE.Mesh
    foil_gold: THREE.Mesh
    foil_gold_2: THREE.Mesh
    plastic_dark: THREE.Mesh
    plastic_white: THREE.Mesh
    tex_01: THREE.Mesh
  }
  materials: {
    aluminum: THREE.MeshStandardMaterial
    black_krinkle: THREE.MeshStandardMaterial
    dish_AO: THREE.MeshStandardMaterial
    foil_gold: THREE.MeshStandardMaterial
    foil_gold_2: THREE.MeshStandardMaterial
    plastic_dark: THREE.MeshStandardMaterial
    plastic_white: THREE.MeshStandardMaterial
    tex_01: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/../CassiniHuygensAwithoutHyugens.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._root.geometry} material={nodes._root.material}>
        <mesh geometry={nodes.aluminum.geometry} material={materials.aluminum} position={[-0.009, -2.44, -4.66]} scale={0.5} />
        <mesh geometry={nodes.black_krinkle.geometry} material={materials.black_krinkle} position={[-0.489, -0.743, 0]} scale={0.5} />
        <mesh geometry={nodes.dish.geometry} material={materials.dish_AO} position={[0.002, 1.932, -0.101]} scale={0.5} />
        <mesh geometry={nodes.foil_gold.geometry} material={materials.foil_gold} position={[0.083, -0.721, -4.587]} scale={0.5} />
        <mesh geometry={nodes.foil_gold_2.geometry} material={materials.foil_gold_2} position={[0.067, 0.624, 0.06]} scale={0.5} />
        <mesh geometry={nodes.plastic_dark.geometry} material={materials.plastic_dark} position={[-0.284, -0.873, 0]} scale={0.5} />
        <mesh geometry={nodes.plastic_white.geometry} material={materials.plastic_white} position={[0, 1.143, 0]} scale={0.5} />
        <mesh geometry={nodes.tex_01.geometry} material={materials.tex_01} scale={0.5} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/../CassiniHuygensAwithoutHyugens.glb')
